apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: idpportal
  namespace: flux-system
spec:
  interval: {{ .Values.gitRepository.interval }}
  url: {{ .Values.gitRepository.url }}
  ref:
    branch: {{ .Values.gitRepository.branch }}
  secretRef:
    name: flux-system
